#! /usr/bin/python3

import argparse
import yaml
import os
import sys
import subprocess
import git
import jinja2
import re
import logging

class Kbxbuilder:
    def __init__(self):
        self.parser = argparse.ArgumentParser()

        subparsers = self.parser.add_subparsers(title='subcommands', help='action to perform', dest='action', required=True)

        parser_build_one = subparsers.add_parser('build-one', help='build one app')
        parser_build_one.add_argument('app')
        parser_build_one.set_defaults(func=self.cmd_build_one)

        parser_build_all = subparsers.add_parser('build-all', help='build all apps')
        parser_build_all.set_defaults(func=self.cmd_build_all)

        self.logger = logging.Logger('kbxbuilder')
        ch = logging.StreamHandler()
        self.logger.addHandler(ch)

        self.subloggers = {}

        self.config_paths = [
            '.',
            '/etc/kaboxer',
        ]

        self.config = {}
        self.apps = {}

        for p in self.config_paths:
            f = os.path.join(p, 'kbxbuilder.config.yaml')
            try:
                self.config = yaml.safe_load(open(f))
                self.config_file = f
                self.logger.info("Loading config file " + f)
                break
            except:
                self.logger.error("Failed when loading config file")
                raise

        def walk(node, replace_needed=False):
            for key, item in node.items():
                if isinstance(item, dict):
                    replace_needed = walk(item, replace_needed)
                else:
                    if re.search('\{\{',item):
                        replace_needed = True
                        t = jinja2.Template(item)
                        node[key] = t.render(config=self.config)
            return replace_needed

        i = 10
        while i > 0:
            i -= 1
            if not walk(self.config):
                break

        if i == 0:
            self.logger.error("Dependency loop in config file")
            sys.exit(1)

        os.makedirs(os.path.dirname(self.config['builder']['logfile']), exist_ok=True)
        logfile = self.config['builder']['logfile']
        ch = logging.FileHandler(logfile)
        ch.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
        self.logger.addHandler(ch)

        for p in self.config_paths:
            f = os.path.join(p, 'kbxbuilder.apps.yaml')
            try:
                self.apps = yaml.safe_load(open(f))
                self.apps_file = f
                self.logger.info ("Loading apps file " + f)
                break
            except:
                pass

    def go(self):
        self.args = self.parser.parse_args()
        self.args.func()

    def build_one(self, app):
        os.makedirs(self.config['builder']['buildlogsdir'], exist_ok=True)
        if app not in self.subloggers:
            logfile = os.path.join(self.config['builder']['buildlogsdir'], app+'.log')
            self.subloggers[app] = logging.FileHandler(logfile)
            self.subloggers[app].setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
            def flt(x):
                try:
                    return x.app == app
                except:
                    return False
            self.subloggers[app].addFilter(flt)
            self.logger.addHandler(self.subloggers[app])
        try:
            buildmode = self.apps[app]['buildmode']
        except:
            self.logger.error("Cannot find how to build "+app, extra={'app':app})
            sys.exit(1)

        os.makedirs(self.config['builder']['workdir'], exist_ok=True)
        checkoutdir = os.path.join(self.config['builder']['workdir'], app)
        try:
            branch = self.apps[app]['branch']
        except KeyError:
            branch = 'master'
        self.logger.debug("Checking out Git repository at "+checkoutdir, extra={'app':app})
        if os.path.isdir(checkoutdir):
            repo = git.Repo(checkoutdir)
            origin = repo.remotes['origin']
            if origin.url != self.apps[app]['git_url']:
                self.logger.debug("Switching remote URL", extra={'app':app})
                git.remote.Remote.remove(repo,'origin')
                git.remote.Remote.add(repo,'origin',self.apps[app]['git_url'])
                origin = repo.remotes['origin']
            else:
                self.logger.debug("Remote already on the correct URL", extra={'app':app})
            origin.fetch('--prune')
        else:
            repo = git.Repo.clone_from(self.apps[app]['git_url'], checkoutdir)
        try:
            repo.git.checkout('remotes/origin/'+branch)
        except:
            repo.git.checkout(branch)

        revid = repo.head.commit.hexsha

        if 'subdir' in self.apps[app]:
            appdir = os.path.join(checkoutdir, self.apps[app]['subdir'])
        else:
            appdir = checkoutdir
        appdir = os.path.abspath(appdir)
        if buildmode == 'kaboxer':
            cmd = "kaboxer build %s" % (app,)
            self.logger.debug("Building kaboxer image: " + cmd, extra={'app':app})
            if subprocess.run(cmd, cwd=appdir, shell=True).returncode != 0:
                self.logger.error("Error when running " + cmd, extra={'app':app})
                sys.exit(1)
            if self.apps[app]['push']:
                cmd = "kaboxer push %s" % (app,)
                self.logger.debug("Pushing to registry: " + cmd, extra={'app':app})
                if subprocess.run(cmd, cwd=appdir, shell=True).returncode != 0:
                    self.logger.error("Error when running " + cmd, extra={'app':app})
                    sys.exit(1)

    def cmd_build_one(self):
        self.logger.info("Building "+self.args.app)
        self.build_one(self.args.app)
        self.logger.info("Built "+self.args.app)

    def cmd_build_all(self):
        self.logger.info("Building all apps")
        for app in self.apps:
            self.logger.info("Building "+app)
            self.build_one(app)
            self.logger.info("Built "+app)
        self.logger.info("Built all apps")

kbxbuilder = Kbxbuilder()
kbxbuilder.go()
