#! /bin/sh

netname=kbx-net
port=8765

if ! docker network ls | grep -q $netname ; then
    docker network --driver bridge $netname
fi

component=$1

common_opts="--network $netname --rm --mount source=kbx-hello,target=/var/lib/kbx-hello"

case $component in
    server)
	docker run $common_opts --publish $port:$port --name kbx-hello-server kbx-hello-server
	;;
    cli)
	docker run $common_opts --tty --interactive --name kbx-hello-cli kbx-hello-cli
	;;
    gui)
	;;
    *)
esac
