#! /bin/sh

netname=kbx-net
port=8765

if ! docker network ls | grep -q $netname ; then
    docker network --driver bridge $netname
fi

component=$1

common_opts="--network $netname --rm --mount source=kbx-hello,target=/var/lib/kbx-hello"

case $component in
    server)
	# Make service available outside container?
	# opts="$opts --publish $port:$port"
	docker run $common_opts $opts --name kbx-hello-server kbx-hello-server
	;;
    cli)
	docker run $common_opts --tty --interactive kbx-hello-cli --host kbx-hello-server
	;;
    gui)
	dispnum=$(echo $DISPLAY | cut -d: -f2 | cut -d. -f1)
	docker run $common_opts --env=DISPLAY --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --volume="/tmp/.X11-unix/X$dispnum:/tmp/.X11-unix/X$dispnum:rw" kbx-hello-gui --host kbx-hello-server
	;;
    *)
	echo "Unknown component"
	exit 1
	;;
esac
