#! /usr/bin/perl

use strict;
use warnings;

use Debian::Debhelper::Dh_Lib;

init();

for my $package (@{ $dh{DOPACKAGES} }) {
  autoscript($package, 'postinst', 'postinst-kaboxer', "s/#PACKAGE#/$package/g");
  autoscript($package, 'postrm', 'postrm-kaboxer', "s/#PACKAGE#/$package/g");
  my $tmp = tmpdir($package);
  install_dir("$tmp/usr/src/kaboxer/$package");
  install_file("debian/$package.Dockerfile", "$tmp/usr/src/kaboxer/$package/Dockerfile");
}

__END__

=head1 NAME

dh_kaboxer - handle kaboxer

=head1 SYNOPSIS

B<dh_kaboxer> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_kaboxer is a debhelper program that is responsible for...

A debhelper addon is also provided.  This makes it possible to just use

  #!/usr/bin/make -f
  %:
          dh $@ --with kaboxer

for F<debian/rules>.

=head1 SEE ALSO

L<debhelper(7)>

=head1 COPYRIGHT AND LICENSE

Based on I<dh_perl_openssl> in the I<perl-openssl-defaults> package by Niko Tyni.

Copyright 2010, Ansgar Burchardt <ansgar@debian.org>

Copyright 2016, Niko Tyni <ntyni@debian.org>

Copyright 2019, Roland Mas <lolando@debian.org>

This program is free software, you can redistribute it and/or modify it under
the same terms as Perl itself.
